apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: zone
      #             operator: In
      #             values:
      #             - ap-south-1a
      containers:
        - name: vprodb
          # args:
          #   - "--ignore-db-dir=lost+found"
          image: narsss1234/vprodb:latest
          # volumeMounts:
          #   - mountPath: /var/lib/mysql
          #     name: vpro-db-data
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-pass
                  name: app-secret
      # volumes:
      #   - name: vpro-db-data
      #     awsElasticBlockStore: 
      #       volumeID: "vol-04800397dbe1a5b20"
      #       fsType: ext4
      # initContainers:
      #   - name: busybox
      #     image: busybox:latest
      #     args: ["rm","-rf","/var/lib/mysql/lost+found"]
      #     volumeMounts:
      #       - mountPath: /var/lib/mysql
      #         name: vpro-db-data
