apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq01
spec:
  selector:
    matchLabels:
      app: vprormq01
  template:
    metadata:
      labels:
        app: vprormq01
    spec:
      containers:
      - name: vprormq01
        image: rabbitmq
        env: 
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                key: rmq-pass
                name: app-secret
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"
        ports:
        - containerPort: 15672
          name: vprormq01-port